spring:
  main:
    allow-circular-references: true
  # 메타데이터 사용을 위한 h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  # redis
  data:
    redis:
      port: 6379
      host: ec2-13-125-169-147.ap-northeast-2.compute.amazonaws.com
      password: jangjjolkit!))$

queue:
  wait: waitingQueue
  job: jobQueue
  max-job-size: 1
